version: "3"

services:
  app:
    container_name: appFrontEnd
    image: docker-init-build
    environment:
      - MONGODB_CONN_STRING
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./pages:/app/pages
      - ./components:/app/components
      - ./dbUtils:/app/dbUtils
      - ./public:/app/public
      - ./styles:/app/styles
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
    networks:
      - test-app
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongoDatabase:/data/db
    networks:
      - test-app
networks:
  test-app:
    driver: bridge
