version: "3"

services:
  app:
    image: docker-init-build
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
